name: "Run tests"

on:
  push:
    branches:
        - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          mamba-version: "*"
          activate-environment: qreports
          environment-file: environment.yaml
          miniforge-variant: Mambaforge
          miniforge-version: 4.9.2-4


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Pytest
        run: |
          pytest tests -svv

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: |
          pip install pre-commit

      - name: Lint
        run: |
          pre-commit run --all-files
